src/Entity/Media.php
<?php

namespace App\Entity;

use App\Repository\MediaRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Gedmo\Mapping\Annotation as Gedmo;

#[Vich\Uploadable]
#[ORM\Entity(repositoryClass: MediaRepository::class)]
class Media
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $createdAt = null;

    #[Gedmo\SortableGroup]
    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    private ?Project $project = null;

    // NOTE: This is not a mapped field of entity metadata, just a simple property.
    #[Vich\UploadableField(mapping: 'media', fileNameProperty: 'mediaName', size: 'mediaSize')]
    private ?File $mediaFile = null;

    #[ORM\Column(type: 'string')]
    private ?string $mediaName = null;

    #[ORM\Column(type: 'integer')]
    private ?int $mediaSize = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $uploadedAt = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\OneToMany(mappedBy: 'sourceMedia', targetEntity: Link::class, orphanRemoval: true)]
    private Collection $fromMeLinks;

    #[ORM\OneToMany(mappedBy: 'targetMedia', targetEntity: Link::class, orphanRemoval: true)]
    private Collection $toMeLinks;

    #[ORM\Column(nullable: false)]
    #[Gedmo\SortablePosition]
    private ?int $orderInProject = null;

    #[ORM\Column(nullable: true)]
    private ?float $initialPitch = null;

    #[ORM\Column(nullable: true)]
    private ?float $initialYaw = null;

    #[ORM\Column(options: ['default' => false])]
    private ?bool $isLuminosityFilterApplied = null;

    // create constructor
    public function __construct()
    {
        $this->createdAt = new \DateTimeImmutable();
        $this->fromMeLinks = new ArrayCollection();
        $this->toMeLinks = new ArrayCollection();
        $this->orderInProject = 0;
        $this->isLuminosityFilterApplied = false;
    }

    public function __toString(): string
    {
        return $this->name;
    }

    /**
     * used by the vichDirectoryNamer to save the media in the right directory.
     * With this directory tree, the media are saved by project owner and then by project.
     */
    public function vichDirectoryName(): string
    {
        return $this->getProject()->getOwner()->getId().'/'.$this->getProject()->getId();
    }

    public function getNodeId(): string
    {
        return 'pano-'.$this->getId();
    }

    public function getInitialPosition(): array
    {
        return [
            'pitch' => $this->getInitialPitch() ?? 0,
            'yaw' => $this->getInitialYaw() ?? 0,
        ];
    }

    public function arrayExport()
    {
        return [
            'id' => $this->getId(),
            'projectId' => $this->getProject()->getId(),
            'name' => $this->getName(),
            'mediaName' => $this->getMediaName(),
            'mediaSize' => $this->getMediaSize(),
            'orderInProject' => $this->getOrderInProject(),
            'uploadedAt' => $this->getUploadedAt()->format('Y-m-d H:i:s'),
            'createdAt' => $this->getCreatedAt()->format('Y-m-d H:i:s'),
            'initialPitch' => $this->getInitialPitch(),
            'initialYaw' => $this->getInitialYaw(),
        ];
    }

    public function arrayImport(array $data): void
    {
        $this->setName($data['name']);
        $this->setMediaName($data['mediaName']);
        $this->setMediaSize($data['mediaSize']);
        $this->setOrderInProject($data['orderInProject']);
        $this->setUploadedAt(new \DateTimeImmutable($data['uploadedAt']));
        $this->setInitialPitch($data['initialPitch']);
        $this->setInitialYaw($data['initialYaw']);
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getProject(): ?Project
    {
        return $this->project;
    }

    public function setProject(?Project $project): self
    {
        $this->project = $project;

        return $this;
    }

    /**
     * If manually uploading a file (i.e. not using Symfony Form) ensure an instance
     * of 'UploadedFile' is injected into this setter to trigger the update. If this
     * bundle's configuration parameter 'inject_on_load' is set to 'true' this setter
     * must be able to accept an instance of 'File' as the bundle will inject one here
     * during Doctrine hydration.
     *
     * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile|null $imageFile
     */
    public function setMediaFile(?File $mediaFile = null): void
    {
        $this->mediaFile = $mediaFile;

        if (null !== $mediaFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->uploadedAt = new \DateTimeImmutable();
        }
    }

    public function getMediaFile(): ?File
    {
        return $this->mediaFile;
    }

    public function setMediaName(?string $mediaName): self
    {
        $this->mediaName = $mediaName;
        return $this;
    }

    public function getMediaName(): ?string
    {
        return $this->mediaName;
    }

    public function setMediaSize(?int $mediaSize): self
    {
        $this->mediaSize = $mediaSize;
        return $this;
    }

    public function getMediaSize(): ?int
    {
        return $this->mediaSize;
    }

    public function getUploadedAt(): ?\DateTimeImmutable
    {
        return $this->uploadedAt;
    }

    public function setUploadedAt(?\DateTimeImmutable $uploadedAt): self
    {
        $this->uploadedAt = $uploadedAt;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return Collection<int, Link>
     */
    public function getFromMeLinks(): Collection
    {
        return $this->fromMeLinks;
    }

    public function addFromMeLink(Link $fromMeLink): self
    {
        if (!$this->fromMeLinks->contains($fromMeLink)) {
            $this->fromMeLinks->add($fromMeLink);
            $fromMeLink->setSourceMedia($this);
        }

        return $this;
    }

    public function removeFromMeLink(Link $fromMeLink): self
    {
        if ($this->fromMeLinks->removeElement($fromMeLink)) {
            // set the owning side to null (unless already changed)
            if ($fromMeLink->getSourceMedia() === $this) {
                $fromMeLink->setSourceMedia(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Link>
     */
    public function getToMeLinks(): Collection
    {
        return $this->toMeLinks;
    }

    public function addToMeLink(Link $toMeLink): self
    {
        if (!$this->toMeLinks->contains($toMeLink)) {
            $this->toMeLinks->add($toMeLink);
            $toMeLink->setTargetMedia($this);
        }

        return $this;
    }

    public function removeToMeLink(Link $toMeLink): self
    {
        if ($this->toMeLinks->removeElement($toMeLink)) {
            // set the owning side to null (unless already changed)
            if ($toMeLink->getTargetMedia() === $this) {
                $toMeLink->setTargetMedia(null);
            }
        }

        return $this;
    }

    public function getOrderInProject(): ?int
    {
        return $this->orderInProject;
    }

    public function setOrderInProject(?int $orderInProject): self
    {
        $this->orderInProject = $orderInProject;

        return $this;
    }

    public function getInitialPitch(): ?float
    {
        return $this->initialPitch ?? 0;
    }

    public function setInitialPitch(?float $initialPitch): self
    {
        $this->initialPitch = $initialPitch;

        return $this;
    }

    public function getInitialYaw(): ?float
    {
        return $this->initialYaw ?? 0;
    }

    public function setInitialYaw(?float $initialYaw): self
    {
        $this->initialYaw = $initialYaw;

        return $this;
    }

    public function isLuminosityFilterApplied(): ?bool
    {
        return $this->isLuminosityFilterApplied;
    }

    public function setIsLuminosityFilterApplied(bool $isLuminosityFilterApplied): self
    {
        $this->isLuminosityFilterApplied = $isLuminosityFilterApplied;

        return $this;
    }
}

src/Form/MediaType.php
<?php

namespace App\Form;

use App\Entity\Media;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Vich\UploaderBundle\Form\Type\VichImageType;

class MediaType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name', TextType::class, [
                'required' => true,
                'label' => 'Name',
            ])
            ->add('mediaFile', VichImageType::class, [
                'required' => false,
                'label' => 'Media',
            ])
            ->add('isLuminosityFilterApplied', null, [
                'required' => false,
                'label' => 'Automatically adjust luminosity',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Media::class,
        ]);
    }
}

templates/media/edit.html.twig
{% extends 'base-aside.html.twig' %}

{% block javascripts %}
    {{ parent() }}
    {{ encore_entry_script_tags('mediaEdit') }}
{% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item">
        <a href="{{ path('app_project_show', {id: media.project.id}) }}">Projet</a>
    </li>
    <li class="breadcrumb-item">
        <a href="{{ path('app_media_show', {id: media.id}) }}">Media</a>
    </li>
{% endblock %}

{% block title %}Edit the media {{ media.name }}{% endblock %}

{% block body %}
    <h1><span class="title-text-light">Edit the media</span> {{ media.name }}</h1>
    {{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-primary">Update media</button>
    {{ form_end(form) }}
{% endblock %}

{% block aside %}
    <p>Move the panorama to set the initial eye direction for this media</p>
    <div
        id="viewer"
        style="width: 100%; height: 30vh;"
        data-panorama="{{ path('app_media_download', {id: media.id}) }}"
        data-initial-position="{{ media.initialPosition|json_encode|escape('html_attr') }}"
    ></div>

{% endblock %}

templates/media/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Add a new Media{% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item">
        <a href="{{ path('app_project_show', {id: project.id}) }}">Projet</a>
    </li>
{% endblock %}

{% block body %}
    {{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-primary">Add media</button>
    {{ form_end(form) }}
{% endblock %}

templates/media/show.html.twig
{% extends 'base-aside.html.twig' %}

{% block javascripts %}
    {{ parent() }}
    {{ encore_entry_script_tags('media') }}
{% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item">
        <a href="{{ path('app_project_show', {id: media.project.id}) }}">Projet</a>
    </li>
    <li class="breadcrumb-item">
        <a href="{{ path('app_media_show', {id: media.id}) }}">Media</a>
    </li>
{% endblock %}

{% block title %}Media{% endblock %}

{% block body %}
    <h1><span class="title-text-light">Media</span> {{ media.name }}</h1>

    <div
        id="viewer"
        style="width: 100%; height: 50vh;"
        data-panorama="{{ path('app_media_download', {id: media.id}) }}"
        data-initial-position="{{ media.initialPosition|json_encode|escape('html_attr') }}"
    ></div>

    <br/>
    <a href="{{ path('app_media_edit', {id: media.id}) }}" class="btn btn-primary">Edit</a>

    <form method="post"  style="display:inline" action="{{ path('app_media_toggle-filters', {'id': media.id}) }}">
        <input type="hidden" name="_token" value="{{ csrf_token('toggleFilters' ~ media.id) }}">
        <button class="btn btn-outline-primary">
            {% if media.isLuminosityFilterApplied %}
                Remove luminosity filter
            {% else %}
                Apply luminosity filter
            {% endif %}
        </button>
    </form>

    <form method="post"  style="display:inline" action="{{ path('app_media_delete', {'id': media.id}) }}" onsubmit="return confirm('Are you sure you want to delete the media {{ media.name }}?');">
        <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ media.id) }}">
        <button class="btn btn-outline-danger">Delete</button>
    </form>

{% endblock %}

{% block aside %}
    <h2>Links from this media</h2>
    {% if fromMeLinks|length == 0 %}
        <div class="alert alert-info" role="alert">No link from this media</div>
    {% else %}
        {% for link in fromMeLinks %}
            <div class="card mb-3 bg-light">
                <div class="card-body">
                    {% if link.isComplete %}
                        <span class="link-badge badge text-bg-success">ok</span>
                    {% else %}
                        <span class="link-badge badge text-bg-warning">uncomplete</span>
                    {% endif %}
                    <small>From: </small>{{ link.sourceMedia.name }}<br/>
                    <small>To: </small>{{ link.targetMedia.name }}<br/>

                    <a href="{{ path('app_link_edit', {id: link.id}) }}" class="btn btn-primary btn-sm">Edit link</a>
                    {% if backLinks['link-' ~ link.id]|default(null) %}
                        <a href="{{ path('app_link_edit', {id: backLinks['link-' ~ link.id]}) }}" class="btn btn-outline-primary btn-sm">Edit backlink</a>
                    {% else %}
                        <form style="display: inline" method="post" action="{{ path('app_link_create_backlink', {'id': link.id}) }}">
                            <input type="hidden" name="_token" value="{{ csrf_token('create_backlink' ~ link.id) }}">
                            <button class="btn btn-primary btn-sm">Create backlink</button>
                        </form>
                    {% endif %}

                    <form style="display: inline" method="post" action="{{ path('app_link_delete', {'id': link.id}) }}" onsubmit="return confirm('Are you sure you want to delete the link from {{ link.sourceMedia.name }} to {{ link.targetMedia.name }} ?');">
                        <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ link.id) }}">
                        <button class="btn btn-outline-danger btn-sm">Delete</button>
                    </form>
                </div>
            </div>
        {% endfor %}
    {% endif %}

    <h2>Create a link</h2>
    {% if targetMediaList|length == 0 %}
        <div class="alert alert-info" role="alert">This media is the only one. We can't create a link to another media.</div>
    {% else %}
        Choose the destination media
        {{ form_start(form) }}
        {{ form_widget(form) }}
        <button class="btn btn-primary">Create a new link</button>
        {{ form_end(form) }}
    {% endif %}
{% endblock %}