src/Entity/Project.php
<?php

namespace App\Entity;

use App\Enum\ProjectRendererEnum;
use App\Repository\ProjectRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ProjectRepository::class)]
class Project
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $owner = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $createdAt = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(nullable: true)]
    private ?int $shareDurationInDays = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $shareUid = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $shareStartedAt = null;

    /**
     * The renderer indicates how we will display the project : It can
     * be a single panorama, a gallery of panoramas or a virtual visit
     */
    #[ORM\Column(length: 50, nullable: true, enumType: ProjectRendererEnum::class)]
    private ?ProjectRendererEnum $renderer;

    public function __construct()
    {
        $this->setCreatedAt(new \DateTimeImmutable());
        $this->setShareDurationInDays(30);
        $this->setRenderer(ProjectRendererEnum::SIMPLE_PANORAMA);
    }

    public function getShareEndedAt(): ?\DateTimeImmutable
    {
        if ($this->getShareStartedAt() === null) {
            return null;
        }
        return $this->getShareStartedAt()->modify('+' . $this->getShareDurationInDays() . ' days');
    }

    public function isShareActive(): bool
    {
        if ($this->getShareStartedAt() === null) {
            return false;
        }
        return $this->getShareEndedAt() > new \DateTimeImmutable();
    }

    public function getShareRemainingDays(): ?int
    {
        if ($this->getShareStartedAt() === null) {
            return null;
        }
        $now = new \DateTimeImmutable();
        $diff = $now->diff($this->getShareEndedAt());
        return $diff->days;
    }

    public function arrayExport() {
        return [
            'id' => $this->getId(),
            'ownerEmail' => $this->getOwner()->getEmail(),
            'ownerId' => $this->getOwner()->getId(),
            'createdAt' => $this->getCreatedAt()->format('Y-m-d H:i:s'),
            'name' => $this->getName(),
            'renderer' => $this->getRenderer() ? $this->getRenderer()->value : null,
        ];
    }
    public function arrayImport(array $data) {
        $this->setName($data['name']);
        $this->setRenderer(ProjectRendererEnum::getEnumCaseByValue($data['renderer']));
        return $this;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getOwner(): ?User
    {
        return $this->owner;
    }

    public function setOwner(?User $owner): self
    {
        $this->owner = $owner;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getShareDurationInDays(): ?int
    {
        return $this->shareDurationInDays;
    }

    public function setShareDurationInDays(?int $shareDurationInDays): self
    {
        $this->shareDurationInDays = $shareDurationInDays;

        return $this;
    }

    public function getShareUid(): ?string
    {
        return $this->shareUid;
    }

    public function setShareUid(?string $shareUid): self
    {
        $this->shareUid = $shareUid;

        return $this;
    }

    public function getShareStartedAt(): ?\DateTimeImmutable
    {
        return $this->shareStartedAt;
    }

    public function setShareStartedAt(?\DateTimeImmutable $shareStartedAt): self
    {
        $this->shareStartedAt = $shareStartedAt;

        return $this;
    }

    public function getRenderer(): ?ProjectRendererEnum
    {
        return $this->renderer;
    }

    public function setRenderer(?ProjectRendererEnum $renderer): self
    {
        $this->renderer = $renderer;

        return $this;
    }
}

src/Form/ProjectType.php
<?php

namespace App\Form;

use App\Entity\Project;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ProjectType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Project::class,
        ]);
    }
}

src/Controller/ProjectController.php
<?php

namespace App\Controller;

use App\Entity\Media;
use App\Entity\Project;
use App\Entity\User;
use App\ExportImport\Exporter;
use App\ExportImport\Importer;
use App\Form\ImportType;
use App\Form\ProjectType;
use App\Repository\MediaRepository;
use App\Repository\ProjectRepository;
use App\Service\MediaManager;
use Kibatic\DatagridBundle\Grid\GridBuilder;
use Kibatic\DatagridBundle\Grid\Template;
use Kibatic\DatagridBundle\Grid\Theme;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Filesystem\Filesystem;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\BadRequestHttpException;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Routing\RouterInterface;
use Symfony\Component\Uid\Uuid;

#[Route('/project')]
class ProjectController extends AbstractController
{
    #[Route('/', name: 'app_project_index', methods: ['GET'])]
    public function index(
        Request $request,
        ProjectRepository $projectRepository,
        GridBuilder $gridBuilder,
    ): Response {
        // deny access if the user is not logged in
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');

        // get current user
        $user = $this->getUser();

        // create query builder filtered by current user
        $queryBuilder = $projectRepository->createQueryBuilder('p')
            ->where('p.owner = :user')
            ->setParameter('user', $user)
            ->orderBy('p.createdAt', 'DESC');
        ;
        $grid = $gridBuilder
            ->create($queryBuilder, $request)
            ->setTheme(Theme::BOOTSTRAP5)
            ->addColumn(
                'Name',
                function (Project $project) {
                    if ($project->isShareActive()) {
                        return sprintf(
                            '%s<br/><span class="text-secondary">shared until %s</span>',
                            $project->getName(),
                            $project->getShareEndedAt()->format('Y-m-d'),
                        );
                    }
                    return sprintf(
                        '%s<br/><span class="text-secondary">Not shared</span>',
                        $project->getName(),
                    );
                },
                Template::TEXT,
                ['escape' => false],
            )
            ->addColumn('Renderer', 'renderer.name')
            ->addColumn(
                'Created at',
                fn(Project $project) => $project->getCreatedAt()->format('Y-m-d'),
                Template::TEXT
            )
            ->addColumn(
                'Actions',
                function (Project $project) {
                    $showButton = [
                        'name' => 'Show',
                        'url' => $this->generateUrl('app_project_show', ['id' => $project->getId()]),
                    ];
                    $editButton = [
                        'name' => 'Edit',
                        'url' => $this->generateUrl('app_project_edit', ['id' => $project->getId()]),
                    ];
                    $previewButton = [
                        'name' => 'Preview',
                        'url' => $this->generateUrl('app_renderer_preview', ['id' => $project->getId()]),
                    ];
                    return [
                        $showButton,
                        //$editButton,
                        $previewButton
                    ];
                },
                Template::ACTIONS
            )
            ->getGrid()
        ;

        return $this->render('project/index.html.twig', [
            'grid' => $grid,
        ]);
    }

    #[Route('/new', name: 'app_project_new', methods: ['GET', 'POST'])]
    public function new(Request $request, ProjectRepository $projectRepository): Response
    {
        // deny access if the user is not logged in
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');

        // get current user
        $user = $this->getUser();

        $project = new Project();
        $project->setOwner($user);
        $form = $this->createForm(ProjectType::class, $project);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $projectRepository->save($project, true);
            $this->addFlash('success', 'Project created successfully.');
            return $this->redirectToRoute('app_project_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('project/new.html.twig', [
            'project' => $project,
            'form' => $form,
        ]);
    }

    #[Route('/import', name: 'app_project_import', methods: ['GET', 'POST'])]
    public function import(
        Request $request,
        Importer $importer
    ): Response
    {
        // deny access if the user is not logged in
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');

        // get current user
        /** @var User $user */
        $user = $this->getUser();

        $form = $this->createForm(ImportType::class);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $file = $form['import_file']->getData();
            $extension = $file->guessExtension();
            if (!$extension) {
                $extension = 'zip';
            }
            $dir = sys_get_temp_dir();
            $filename = Uuid::v4() . '.' . $extension;
            $file->move($dir, $filename);
            $zipFile = $dir . '/' . $filename;
            $project = $importer->importProject($zipFile, $user);
            $filesystem = new Filesystem();
            $filesystem->remove($zipFile);
            $this->addFlash('success', 'Project imported successfully.');
            return $this->redirectToRoute('app_project_show', ['id' => $project->getId()], Response::HTTP_SEE_OTHER);
        }
        return $this->renderForm('project/import.html.twig', [
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_project_show', methods: ['GET'])]
    public function show(
        Project $project,
        MediaRepository $mediaRepository,
        GridBuilder $gridBuilder,
        Request $request,
        RouterInterface $router
    ): Response {
        // deny access if the user is not logged in
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');

        // get current user
        $user = $this->getUser();

        // deny access if the user is not the owner of the project
        if ($project->getOwner() !== $user) {
            throw $this->createAccessDeniedException();
        }

        // create query builder for Media filtered by current user
        $queryBuilder = $mediaRepository->createQueryBuilder('m')
            ->where('m.project = :project')
            ->setParameter('project', $project)
            ->orderBy('m.orderInProject', 'ASC')
        ;
        $grid = $gridBuilder
            ->create($queryBuilder, $request)
            ->setItemsPerPage(100)
            ->setTheme(Theme::BOOTSTRAP5)
            ->addColumn(
                'Media',
                fn(Media $media) => sprintf(
                    '<img src="%s" alt="%s" width="100" />',
                    $router->generate('app_media_thumbnail', [ 'id' => $media->getId() ]),
                    $media->getName()
                ),
                Template::TEXT,
                [ 'escape' => false ]

            )
            ->addColumn(
                'Name',
                'name'
            )
            ->addColumn(
                'Infos',
                fn(Media $media) => sprintf(
                    '
                    order: %s<br/>
                    from links : %s<br/>
                    to links : %s
                    ',
                    $media->getOrderInProject(),
                    count($media->getFromMeLinks()),
                    count($media->getToMeLinks())
                ),
                Template::TEXT,
                [ 'escape' => false ]
            )
            ->addColumn(
                'Actions',
                fn(Media $media) => [
                    [
                        'name' => 'Show',
                        'url' => $this->generateUrl('app_media_show', ['id' => $media->getId()]),
                    ]
                ],
                Template::ACTIONS
            )
            ->getGrid()
        ;

        return $this->render('project/show.html.twig', [
            'project' => $project,
            'grid' => $grid,
        ]);
    }


    #[Route('/{id}/export', name: 'app_project_export', methods: ['GET'])]
    public function export(
        Project $project,
        Exporter $exporter,
        Request $request,
        RouterInterface $router
    ): Response
    {
        // deny access if the user is not logged in
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');

        // get current user
        $user = $this->getUser();

        // deny access if the user is not the owner of the project
        if ($project->getOwner() !== $user) {
            throw $this->createAccessDeniedException();
        }

        return $exporter->streamResponse($project);
    }


    #[Route('/{id}/edit', name: 'app_project_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Project $project, ProjectRepository $projectRepository): Response
    {
        $form = $this->createForm(ProjectType::class, $project);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $projectRepository->save($project, true);
            $this->addFlash('success', 'Project updated successfully.');
            return $this->redirectToRoute('app_project_show', ['id' => $project->getId()], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('project/edit.html.twig', [

templates/project/_delete_form.html.twig
<form style="display:inline" method="post" action="{{ path('app_project_delete', {'id': project.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ project.id) }}">
    <button class="btn btn-outline-danger">Delete</button>
</form>

templates/project/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-primary">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/project/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Project{% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item">
        <a href="{{ path('app_project_show', {id: project.id}) }}">Projet</a>
    </li>
{% endblock %}

{% block body %}
    <h1><span class="title-text-light">Edit project</span> {{ project.name }}</h1>

    {{ include('project/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_project_index') }}">back to list</a>

    {{ include('project/_delete_form.html.twig') }}
{% endblock %}

templates/project/gallery.html.twig
{% extends 'share-base.html.twig' %}

{% block javascripts %}
    {{ parent() }}
    {{ encore_entry_script_tags('gallery') }}
{% endblock %}

{% block title %}Project: {{ project.name }}{% endblock %}

{% block body %}
    <div
            id="viewer"
            style="width: 100vw;height: 100vh;"
            data-items="{{ items|json_encode|escape('html_attr') }}"
            data-caption="{{ project.name }}"
            data-panorama="{{ items.0.panorama }}"
    >

    </div>

{% endblock %}

templates/project/import.html.twig
{% extends 'base.html.twig' %}

{% block title %}Import Project{% endblock %}

{% block body %}
    <h1>Import a project from a file</h1>

    {{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-primary">Import file</button>
    {{ form_end(form) }}
{% endblock %}

templates/project/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Visit list{% endblock %}

{% block body %}
    <h1>Visit list</h1>

    {% include grid.theme ~ '/datagrid.html.twig' %}

    <a href="{{ path('app_project_new') }}" class="btn btn-primary">Create a new project</a>
    <a href="{{ path('app_project_import') }}" class="btn btn-primary">Import from a file</a>
{% endblock %}

templates/project/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Project{% endblock %}

{% block body %}
    <h1>Create new Project</h1>

    {{ include('project/_form.html.twig') }}
{% endblock %}

templates/project/show.html.twig
{% extends 'base-aside.html.twig' %}

{% block body_size %}col-6{% endblock %}

{% block title %}{{ project.name }} : projet openvv{% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item">
        <a href="{{ path('app_project_show', {id: project.id}) }}">Projet</a>
    </li>
{% endblock %}

{% block body %}
    <h1><span class="title-text-light">Projet</span> {{ project.name }}</h1>
    <div class="container">
        <div class="row gy-2">
            <div class="card">
                <div class="card-header">
                    Sharing
                </div>
                <div class="card-body">
                    {% if project.isShareActive %}
                        Shared until {{ project.shareEndedAt|date('m/d/Y') }}<br/>
                        Shared URL : <a href="{{ url('app_renderer_view', {shareUid: project.shareUid}) }}">{{ url('app_renderer_view', {shareUid: project.shareUid}) }}</a><br/>
                    {% else %}
                        Not shared
                    {% endif %}
                </div>
            </div>
            <div class="card">
                <div class="card-header">
                    Informations
                </div>
                <div class="card-body">
                    Rendering : {{ project.renderer.name }}<br/>
                    Created at : {{ project.createdAt|date('Y-m-d H:i:s') }}
                </div>
            </div>
        </div>
    </div>

    <a href="{{ path('app_project_edit', {id: project.id}) }}" class="btn btn-primary">edit</a>
    <a href="{{ path('app_renderer_preview', {id: project.id}) }}" class="btn btn-primary">preview</a>
    <a href="{{ path('app_project_export', {id: project.id}) }}" class="btn btn-outline-primary">export</a>
    {% if project.isShareActive %}
        <form style="display:inline" method="post" action="{{ path('app_share_delete', {'id': project.id}) }}" onsubmit="return confirm('Are you sure you want to unshare this item ? The id of the sharing will be lost.');">
            <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ project.id) }}">
            <button class="btn btn-outline-primary">Unshare</button>
        </form>
    {% else %}
        <a href="{{ path('app_share_new', {id: project.id}) }}" class="btn btn-outline-primary">Share</a>
    {% endif %}

    {{ include('project/_delete_form.html.twig') }}
{% endblock %}

{% block aside %}
    <h2>Médias</h2>
    <a href="{{ path('app_media_new', {'project': project.id}) }}" class="btn btn-primary">Ajouter un média</a>
    <form style="display:inline" method="post" action="{{ path('app_projet_media_reverse_order', {'project': project.id}) }}">
        <input type="hidden" name="_token" value="{{ csrf_token('reverseorder' ~ project.id) }}">
        <button class="btn btn-outline-primary">Reverse order</button>
    </form>

    {% include grid.theme ~ '/datagrid.html.twig' %}
{% endblock %}